name: Terraform Security Scan

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  checkov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Checkov Scan
        uses: bridgecrewio/checkov-action@master