name: Vault Terraform Azure Demo

on:
  push:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Vault using GitHub OIDC
        uses: hashicorp/vault-action@v2
        with:
          url: http://20.235.72.161:8200
          method: jwt
          role: github-actions-role
          exportToken: true

      - name: Install Vault CLI
        run: |
          wget https://releases.hashicorp.com/vault/1.17.2/vault_1.17.2_linux_amd64.zip
          unzip vault_1.17.2_linux_amd64.zip
          sudo mv vault /usr/local/bin/

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get Dynamic Azure Credentials from Vault
        run: |
          vault read -format=json azure/creds/terraform-role > creds.json

          echo "ARM_CLIENT_ID=$(jq -r '.data.client_id' creds.json)" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=$(jq -r '.data.client_secret' creds.json)" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=$(jq -r '.data.subscription_id' creds.json)" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=$(jq -r '.data.tenant_id' creds.json)" >> $GITHUB_ENV
        env:
          VAULT_ADDR: http://20.235.72.161:8200

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
